argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, get, *, allow
        p, role:org-admin, repositories, get, *, allow
        p, role:org-admin, repositories, create, *, allow
        p, role:org-admin, repositories, update, *, allow
        p, role:org-admin, repositories, delete, *, allow
        g, devops, role:admin

    config:
      users.anonymous.enabled: "true"
      users.session.duration: "1h"
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - name: prometheus-operator
          type: helm
          url: https://prometheus-community.github.io/helm-charts
        - name: stable
          type: helm
          url: https://charts.helm.sh/stable 
        - url: https://github.com/avpatel257/argo-poc.git
          passwordSecret:
            name: git-credential
            key: password
          usernameSecret:
            name: git-credential
            key: username                     
        - url: https://github.com/baps-apps/sso-api-config.git
          passwordSecret:
            name: git-credential
            key: password
          usernameSecret:
            name: git-credential
            key: username                     
