{{- if eq "nonprod" $.Values.aws.cluster }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: baps-apps/dev
    repoURL: https://github.com/avpatel257/argo-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
{{- end }}