cert-manager:
  installCRDs: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: cert-manager
          repository: https://charts.jetstack.io